import type { LocaleCode } from "../types";

const zh = {
  common: {
    notAvailable: "暂无",
    loadingFailed: "加载失败。",
    save: "保存",
    delete: "删除",
    cancel: "取消",
  },
  assistant: {
    sidebarKicker: "研究台",
    heroKicker: "上下文优先的助手",
    noticeDegraded: "远端 AI 服务当前不可用，本次结果已自动降级为站内本地回答。",
    title: "AI 助手",
    subtitle: "优先检索站内的问题、答案和文章，再整理成可继续追问的分析记录。",
    newThread: "新会话",
    emptyThreadSummary: "暂无摘要",
    deleteThreadAria: (title: string) => `删除会话 ${title}`,
    emptyThreads: "还没有历史会话。",
    threadTitleFallback: "开始一个新会话",
    threadSubtitle: "回答默认优先引用社区里的问题、答案和文章，避免变成没有上下文的通用闲聊。",
    regenerate: "重新生成",
    emptyState: "输入一个技术问题，AI 助手会先检索站内内容，再生成带引用的建议。",
    assistantName: "AI 助手",
    assistantSourceRemote: "模型回答",
    assistantSourceLocal: "本地兜底",
    assistantGenerating: "正在生成",
    referencesHint: "输入 @ 搜索要引用的问题、文章、回答或评论。",
    referencesSelected: "已选引用",
    referencesSearching: "正在搜索引用...",
    referencesEmpty: "没有匹配的引用结果。",
    referencesUnavailable: "引用搜索暂时不可用，请稍后重试或重启后端。",
    referencesRemove: "移除引用",
    referenceTypeQuestion: "问题",
    referenceTypeArticle: "文章",
    referenceTypeAnswer: "回答",
    referenceTypeComment: "评论",
    you: "你",
    copy: "复制",
    textareaPlaceholder: "例如：如何判断该用 useState 还是 useReducer？",
    submitPending: "分析中...",
    submitIdle: "开始分析",
  },
  tutorials: {
    title: "视频教程",
    heroKicker: "课程库",
    heroTitle: "用课程页、章节线索和可嵌入视频，把技术内容排成一张更完整的学习地图。",
    heroBody: "课程不只是视频入口，还保留结构、标签、难度、进度和直接进入 Playground 的练习通道。",
    filterKicker: "筛选",
    filterTitle: "筛选视角",
    difficultyLabel: "难度等级",
    difficultyAll: "全部难度",
    difficultyBeginner: "入门",
    difficultyIntermediate: "进阶",
    difficultyAdvanced: "高级",
    tagLabel: "主题标签",
    tagAll: "全部标签",
    count: (count: number) => `当前共展示 ${count} 门课程。筛选会同步到 URL，方便直接分享某个学习视图。`,
    lessons: (count: number) => `${count} 节`,
    progress: (value: number) => `进度 ${value}%`,
    viewCourse: "查看课程",
    empty: "当前筛选下没有教程。",
  },
  tutorialDetail: {
    notFound: "教程不存在",
    backToList: "返回教程列表",
    openPlayground: "在 Playground 打开",
    recordProgress: "记录进度",
    currentLessonKicker: "当前课时",
    railKicker: "章节导航",
    chapters: "课程章节",
    progress: (value: number) => `进度 ${value}%`,
    minutes: (count: number) => `${count} 分钟`,
    difficultyBeginner: "入门",
    difficultyIntermediate: "进阶",
    difficultyAdvanced: "高级",
  },
  playground: {
    heroKicker: "浏览器实验台",
    heroTitle: "把问题里的代码片段直接拖进浏览器实验台。",
    heroBody: "Playground 保持“随手试验”的速度，但版式上更像一张工作台：左边代码，右边结果，顶部是模板与分享控制。",
    reset: "重置",
    run: "运行",
    share: "复制分享链接",
    titlePlaceholder: "Playground 标题",
    preview: "预览",
    previewKicker: "实时预览",
    sandboxLabel: "沙箱",
    defaultTitle: "新建 Playground",
    importedTitle: "导入 Playground",
  },
  developers: {
    title: "开放平台",
    heroKicker: "开发者平台",
    heroBody: "首期只开放只读公共 API，但页面和文档已经按产品入口组织好：拿 Key、看文档、拉公开数据。",
    docsKicker: "文档",
    docsTitle: "API 文档",
    docsBody: "查看 OpenAPI、请求示例、错误码和速率限制说明。",
    keysKicker: "凭证",
    keysTitle: "管理 API Key",
    keysBody: "创建和吊销 Key，当前每个账号最多保留 2 个有效 Key。",
    scopeKicker: "范围",
    scopeTitle: "只读公共资源",
    scopeBody: "开放问题、答案、文章、标签、热门话题与公开用户主页的查询能力。",
  },
  developerKeys: {
    title: "API Keys",
    heroKicker: "开发者密钥",
    heroBody: "只读公共 API 通过 `x-api-key` 请求头鉴权。新 key 只展示一次，建议立刻保存。",
    inputLabel: "Key 名称",
    create: "创建 API Key",
    revealedSecret: (secret: string) => `新 Key 只展示一次：${secret}`,
    keyDossier: "Key 档案",
    prefix: (value: string) => `Prefix: ${value}`,
    createdAt: (createdAt: string, lastUsedAt?: string | null) =>
      `创建于 ${createdAt} · 最近使用 ${lastUsedAt || "暂无"}`,
    revoked: "已吊销",
    revoke: "吊销",
    defaultName: "Public data key",
  },
  developerDocs: {
    title: "API 文档",
    heroKicker: "接口参考",
    heroBody: "公共读接口使用 `x-api-key` 鉴权，文档页会展示参数、返回结构、错误码与调用示例。",
    authKicker: "认证",
    authTitle: "认证方式",
    authBody: "所有公开接口都要求在请求头里带 `x-api-key`。",
    limitsKicker: "限流",
    rateLimitTitle: "限流",
    rateLimitBody: (count: number) => `默认每小时 ${count} 次，请超限后等待窗口恢复。`,
    versionKicker: "版本",
    curlTitle: "快速示例",
    parameters: "参数",
    responses: "响应",
    errorResponses: "错误码",
    emptyParameters: "无参数。",
    loadFailed: "文档加载失败。",
    responseExample: "示例返回",
    noExample: "暂无示例。",
    requiredBadge: "必填",
  },
  adminTutorials: {
    required: "必填",
    optional: "选填",
    saveFailed: "教程保存失败",
    submitFailed: "提交失败，请确认后端服务已启动并可访问",
    titleMin: "请填写教程标题，至少 2 个字",
    summaryMin: "请填写教程摘要，至少 10 个字",
    descriptionMin: "请填写课程介绍，至少 10 个字",
    coverUrlInvalid: "封面地址必须是合法 URL，或留空",
    tagsMax: "课程标签最多填写 6 个",
    lessonsMin: "至少添加 1 个课时",
    lessonTitleMin: (index: number) => `请填写第 ${index} 个课时的标题，至少 2 个字`,
    lessonDescriptionMin: (index: number) => `请填写第 ${index} 个课时的说明，至少 2 个字`,
    lessonVideoUrlInvalid: (index: number) => `第 ${index} 个课时的视频地址必须是合法 URL`,
    lessonDurationInvalid: (index: number) => `第 ${index} 个课时的时长不能小于 0`,
    starterFilesInvalid: (index: number) => `第 ${index} 个课时的 Starter files 必须是合法 JSON 对象`,
    newLessonTitle: "新课时",
    newLessonDescription: "补充本节课的学习重点。",
    pageTitle: "教程管理",
    pageSubtitle: "课程 CRUD 与章节配置",
    new: "新建",
    lessonsSummary: (count: number, difficulty: string) => `${count} 节 · ${difficulty}`,
    saved: "教程已保存",
    fieldTitle: "标题",
    fieldTitleHint: "课程在前台列表和详情页显示的主标题。",
    fieldCover: "封面",
    fieldCoverHint: "课程封面图片 URL。可以留空，留空时前台使用默认占位样式。",
    fieldDifficulty: "难度",
    fieldDifficultyHint: "用于告诉用户课程适合的学习阶段。",
    difficultyBeginner: "入门",
    difficultyIntermediate: "进阶",
    difficultyAdvanced: "高级",
    fieldTags: "标签（逗号分隔）",
    fieldTagsHint: "帮助用户筛选课程。多个标签请用英文逗号分隔，最多 6 个。",
    fieldSummary: "摘要",
    fieldSummaryHint: "课程卡片上的简短介绍，建议写清学习收益和适合对象。",
    fieldDescription: "课程介绍（Markdown）",
    fieldDescriptionHint: "课程详情页的长说明，可以写课程目标、适用人群和章节安排。",
    fieldPublished: "发布状态",
    fieldPublishedHint: "勾选后前台用户可看到这门课程；取消勾选时只在后台保留。",
    publishCourse: "发布课程",
    lessonsTitle: "课时",
    lessonsHint: "每个课时至少要有标题、说明、视频地址。Starter 模板和 Starter files 仅在需要带入 Playground 时填写。",
    addLesson: "新增课时",
    lessonCardTitle: (index: number) => `课时 ${index}`,
    deleteLesson: "删除",
    lessonTitle: "课时标题",
    lessonTitleHint: "用户在章节列表里看到的标题。",
    lessonTitlePlaceholder: "课时标题",
    lessonVideo: "视频地址",
    lessonVideoHint: "只支持 YouTube、Bilibili、Vimeo 的合法链接。",
    lessonVideoPlaceholder: "视频地址",
    lessonDescription: "课时说明",
    lessonDescriptionHint: "描述这一课会讲什么、适合解决什么问题。",
    lessonDescriptionPlaceholder: "课时说明",
    lessonSort: "排序",
    lessonSortHint: "数字越小越靠前；留空时默认按当前顺序保存。",
    lessonSortPlaceholder: "排序",
    lessonDuration: "时长（秒）",
    lessonDurationHint: "用于展示课程时长和进度。",
    lessonDurationPlaceholder: "时长(秒)",
    starterTemplate: "Starter 模板",
    starterTemplateHint: "如果这节课要一键带到 Playground，选择对应模板；否则留空。",
    starterTemplateNone: "无 starter",
    starterTemplateHtml: "HTML",
    starterTemplateTypescript: "TypeScript",
    starterTemplateReact: "React",
    starterFiles: "Starter files JSON",
    starterFilesHint: '可选。填写后会作为 Playground 初始文件，例如 {"App.tsx":"..."}。必须是 JSON 对象。',
    starterFilesPlaceholder: 'Starter files JSON，例如 {"App.tsx":"..."}',
    deleteTutorial: "删除教程",
    saveTutorial: "保存教程",
  },
  chat: {
    title: "问题讨论",
    onlineCount: (count: number) => `在线 ${count} 人`,
    empty: "还没有讨论消息，先发第一条。",
    placeholder: "围绕当前问题发起实时讨论...",
    sending: "发送中...",
    send: "发送消息",
    loginToJoin: "登录后可加入实时讨论。",
    connecting: "连接中...",
    connected: "已连接",
    reconnecting: (attempt: number) => `正在重连（第 ${attempt} 次）...`,
    disconnected: "实时连接已断开。",
    reconnected: "已重新连接。",
    retrySend: "重试发送",
    sendFailed: (message: string) => `发送失败：${message}`,
  },
} as const;

const en = {
  common: {
    notAvailable: "N/A",
    loadingFailed: "Failed to load.",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
  },
  assistant: {
    sidebarKicker: "Research desk",
    heroKicker: "Context-first assistant",
    noticeDegraded: "The remote AI provider is unavailable. This reply was downgraded to a local site-based answer.",
    title: "Assistant",
    subtitle: "Search questions, answers, and articles first, then turn them into follow-up-ready analysis.",
    newThread: "New thread",
    emptyThreadSummary: "No summary yet",
    deleteThreadAria: (title: string) => `Delete thread ${title}`,
    emptyThreads: "No conversation history yet.",
    threadTitleFallback: "Start a new thread",
    threadSubtitle: "Replies prioritize community questions, answers, and articles instead of generic chat.",
    regenerate: "Regenerate",
    emptyState: "Ask a technical question and the assistant will search site content before replying with citations.",
    assistantName: "Assistant",
    assistantSourceRemote: "Model reply",
    assistantSourceLocal: "Local fallback",
    assistantGenerating: "Generating",
    referencesHint: "Type @ to search questions, articles, answers, or comments to cite.",
    referencesSelected: "Selected references",
    referencesSearching: "Searching references...",
    referencesEmpty: "No matching references.",
    referencesUnavailable: "Reference search is temporarily unavailable. Try again later or restart the API server.",
    referencesRemove: "Remove reference",
    referenceTypeQuestion: "Question",
    referenceTypeArticle: "Article",
    referenceTypeAnswer: "Answer",
    referenceTypeComment: "Comment",
    you: "You",
    copy: "Copy",
    textareaPlaceholder: "For example: how do I decide between useState and useReducer?",
    submitPending: "Analyzing...",
    submitIdle: "Analyze",
  },
  tutorials: {
    title: "Tutorials",
    heroKicker: "Tutorial library",
    heroTitle: "Turn lessons, chapters, and embeddable videos into a clearer map for learning technical topics.",
    heroBody: "Each course keeps structure, tags, difficulty, progress, and a direct path into the Playground.",
    filterKicker: "Refine",
    filterTitle: "Refine",
    difficultyLabel: "Difficulty",
    difficultyAll: "All levels",
    difficultyBeginner: "Beginner",
    difficultyIntermediate: "Intermediate",
    difficultyAdvanced: "Advanced",
    tagLabel: "Tag",
    tagAll: "All tags",
    count: (count: number) => `${count} courses match the current filters. Filters stay in the URL so this view is shareable.`,
    lessons: (count: number) => `${count} lessons`,
    progress: (value: number) => `Progress ${value}%`,
    viewCourse: "Open course",
    empty: "No tutorials match the current filters.",
  },
  tutorialDetail: {
    notFound: "Tutorial not found",
    backToList: "Back to tutorials",
    openPlayground: "Open in Playground",
    recordProgress: "Save progress",
    currentLessonKicker: "Current lesson",
    railKicker: "Lesson rail",
    chapters: "Course chapters",
    progress: (value: number) => `Progress ${value}%`,
    minutes: (count: number) => `${count} min`,
    difficultyBeginner: "Beginner",
    difficultyIntermediate: "Intermediate",
    difficultyAdvanced: "Advanced",
  },
  playground: {
    heroKicker: "Browser lab",
    heroTitle: "Drop a code snippet from any thread straight into a browser lab.",
    heroBody: "The Playground keeps the speed of quick experiments, but the layout feels more like a workbench: code on the left, output on the right, controls on top.",
    reset: "Reset",
    run: "Run",
    share: "Copy share link",
    titlePlaceholder: "Playground title",
    preview: "Preview",
    previewKicker: "Live frame",
    sandboxLabel: "Sandbox",
    defaultTitle: "New Playground",
    importedTitle: "Imported Playground",
  },
  developers: {
    title: "Developer platform",
    heroKicker: "Developer platform",
    heroBody: "The first release only exposes read-only public APIs, but the entry points already cover keys, docs, and public data access.",
    docsKicker: "Reference",
    docsTitle: "API docs",
    docsBody: "Browse OpenAPI details, request examples, error codes, and rate limits.",
    keysKicker: "Credentials",
    keysTitle: "Manage API keys",
    keysBody: "Create and revoke keys. Each account can keep up to 2 active keys.",
    scopeKicker: "Scope",
    scopeTitle: "Read-only public resources",
    scopeBody: "Questions, answers, articles, tags, hot topics, and public profiles are available.",
  },
  developerKeys: {
    title: "API Keys",
    heroKicker: "Developer keys",
    heroBody: "The public read-only API uses the `x-api-key` header. A new key is shown once, so save it immediately.",
    inputLabel: "Key name",
    create: "Create API key",
    revealedSecret: (secret: string) => `This key is shown only once: ${secret}`,
    keyDossier: "Key dossier",
    prefix: (value: string) => `Prefix: ${value}`,
    createdAt: (createdAt: string, lastUsedAt?: string | null) =>
      `Created ${createdAt} · Last used ${lastUsedAt || "never"}`,
    revoked: "Revoked",
    revoke: "Revoke",
    defaultName: "Public data key",
  },
  developerDocs: {
    title: "API docs",
    heroKicker: "Reference",
    heroBody: "Public read endpoints use `x-api-key`. This page shows parameters, responses, error codes, and request examples.",
    authKicker: "Auth",
    authTitle: "Authentication",
    authBody: "Every public endpoint requires an `x-api-key` header.",
    limitsKicker: "Limits",
    rateLimitTitle: "Rate limit",
    rateLimitBody: (count: number) => `${count} requests per hour by default. Wait for the next window when you hit the limit.`,
    versionKicker: "Version",
    curlTitle: "Quick example",
    parameters: "Parameters",
    responses: "Responses",
    errorResponses: "Errors",
    emptyParameters: "No parameters.",
    loadFailed: "Failed to load the API document.",
    responseExample: "Example response",
    noExample: "No example provided.",
    requiredBadge: "required",
  },
  adminTutorials: {
    required: "Required",
    optional: "Optional",
    saveFailed: "Failed to save the tutorial",
    submitFailed: "Request failed. Make sure the backend is running and reachable.",
    titleMin: "Tutorial title must be at least 2 characters",
    summaryMin: "Tutorial summary must be at least 10 characters",
    descriptionMin: "Tutorial description must be at least 10 characters",
    coverUrlInvalid: "Cover must be a valid URL or left blank",
    tagsMax: "Use at most 6 tutorial tags",
    lessonsMin: "Add at least one lesson",
    lessonTitleMin: (index: number) => `Lesson ${index} title must be at least 2 characters`,
    lessonDescriptionMin: (index: number) => `Lesson ${index} description must be at least 2 characters`,
    lessonVideoUrlInvalid: (index: number) => `Lesson ${index} video URL must be a valid URL`,
    lessonDurationInvalid: (index: number) => `Lesson ${index} duration cannot be negative`,
    starterFilesInvalid: (index: number) => `Lesson ${index} starter files must be a valid JSON object`,
    newLessonTitle: "New lesson",
    newLessonDescription: "Add the key learning goal for this lesson.",
    pageTitle: "Tutorial admin",
    pageSubtitle: "Course CRUD and chapter setup",
    new: "New",
    lessonsSummary: (count: number, difficulty: string) => `${count} lessons · ${difficulty}`,
    saved: "Tutorial saved",
    fieldTitle: "Title",
    fieldTitleHint: "The main title shown in the public list and detail page.",
    fieldCover: "Cover",
    fieldCoverHint: "A cover image URL. Leave blank to use the default placeholder style.",
    fieldDifficulty: "Difficulty",
    fieldDifficultyHint: "Helps users understand the intended learning level.",
    difficultyBeginner: "Beginner",
    difficultyIntermediate: "Intermediate",
    difficultyAdvanced: "Advanced",
    fieldTags: "Tags (comma separated)",
    fieldTagsHint: "Helps users filter courses. Use commas and keep the total at 6 or fewer.",
    fieldSummary: "Summary",
    fieldSummaryHint: "A short card summary that explains who the course is for and what they will gain.",
    fieldDescription: "Description (Markdown)",
    fieldDescriptionHint: "The long description for the detail page, including goals, audience, and chapter plan.",
    fieldPublished: "Publish status",
    fieldPublishedHint: "Published courses are visible on the frontend. Unpublished ones stay in admin only.",
    publishCourse: "Publish course",
    lessonsTitle: "Lessons",
    lessonsHint: "Each lesson needs a title, summary, and video URL. Starter template and files are only needed when opening the lesson in Playground.",
    addLesson: "Add lesson",
    lessonCardTitle: (index: number) => `Lesson ${index}`,
    deleteLesson: "Delete",
    lessonTitle: "Lesson title",
    lessonTitleHint: "The title shown in the chapter list.",
    lessonTitlePlaceholder: "Lesson title",
    lessonVideo: "Video URL",
    lessonVideoHint: "Only valid YouTube, Bilibili, or Vimeo links are accepted.",
    lessonVideoPlaceholder: "Video URL",
    lessonDescription: "Lesson summary",
    lessonDescriptionHint: "Describe what this lesson covers and what problem it helps solve.",
    lessonDescriptionPlaceholder: "Lesson summary",
    lessonSort: "Sort order",
    lessonSortHint: "Lower numbers appear first. Leave empty to save in the current order.",
    lessonSortPlaceholder: "Sort order",
    lessonDuration: "Duration (seconds)",
    lessonDurationHint: "Used to display lesson duration and progress.",
    lessonDurationPlaceholder: "Duration (seconds)",
    starterTemplate: "Starter template",
    starterTemplateHint: "Choose a template if this lesson should open in Playground. Leave blank otherwise.",
    starterTemplateNone: "No starter",
    starterTemplateHtml: "HTML",
    starterTemplateTypescript: "TypeScript",
    starterTemplateReact: "React",
    starterFiles: "Starter files JSON",
    starterFilesHint: 'Optional. These become the initial Playground files, for example {"App.tsx":"..."}. Must be a JSON object.',
    starterFilesPlaceholder: 'Starter files JSON, for example {"App.tsx":"..."}',
    deleteTutorial: "Delete tutorial",
    saveTutorial: "Save tutorial",
  },
  chat: {
    title: "Live discussion",
    onlineCount: (count: number) => `${count} online`,
    empty: "No discussion messages yet. Start the first one.",
    placeholder: "Start a live discussion around this question...",
    sending: "Sending...",
    send: "Send message",
    loginToJoin: "Log in to join the live discussion.",
    connecting: "Connecting...",
    connected: "Connected",
    reconnecting: (attempt: number) => `Reconnecting (attempt ${attempt})...`,
    disconnected: "Realtime connection lost.",
    reconnected: "Reconnected.",
    retrySend: "Retry send",
    sendFailed: (message: string) => `Failed to send: ${message}`,
  },
} as const;

export const getP3Copy = (locale: LocaleCode) => (locale === "en-US" ? en : zh);
